// Submission Readiness Engine v0.5 (master Phase 4) — package assembler.
//
// Given a Bonfire opportunity, build a single ZIP containing:
//   /proposal/         OpportunityOutputs (markdown rendered to PDF + raw .md kept too)
//   /vault/            Evergreen Documents (scope='global' OR scope='bid' for THIS opp)
//   /attachments/      OpportunityAttachments (the original RFP files)
//   /manifest.json     full inventory + readiness summary
//   /README.md         human-readable cover page
//
// Streams the ZIP back via archiver. Idempotent — same opp + same vault
// state produces the same package. No persistence on this side; the
// client downloads, agency receives.

const path = require('path');
const fs = require('fs');
// archiver is lazy-required inside streamPackage so the module loads
// cleanly in test contexts that don't exercise the ZIP path. (archiver's
// internal module graph trips Jest's CommonJS parser otherwise.)
const {
  Document, OpportunityAttachment, BonfireOpportunity, OpportunityOutput,
} = require('../models');
const { Op } = require('sequelize');
const docTypes = require('../documents/documentTypes');
const renderer = require('../documents/documentRenderer.service');
const docStorage = require('../documents/storage.adapter');
const attachStorage = require('./attachmentFetcher.service');
const profileSvc = require('../oied/profile.service');
const readiness = require('./bonfireReadiness.service');
const logger = require('../logging/logger');

function safeName(s) {
  return String(s || 'untitled').replace(/[^\w.\-() ]+/g, '_').slice(0, 200);
}

async function loadVaultDocsForOpp({ organizationId, bonfireOpportunityId }) {
  return Document.findAll({
    where: {
      organizationId,
      isActive: true,
      [Op.or]: [
        { scope: 'global' },
        { scope: 'bid', scopeId: String(bonfireOpportunityId) },
      ],
    },
    order: [
      [require('sequelize').literal(`CASE WHEN scope = 'bid' THEN 0 ELSE 1 END`), 'ASC'],
      ['type', 'ASC'],
      ['version', 'DESC'],
    ],
  });
}

async function loadOutputsForOpp({ opportunityId }) {
  // OpportunityOutput.opportunityId references the unified Opportunity table,
  // not BonfireOpportunity. The existing actionGenerator can be triggered against
  // either, but for v0.5 we only ship outputs that are explicitly tied via the
  // opportunityId arg the caller passes in. Bonfire-only path: pass null and skip.
  if (!opportunityId) return [];
  return OpportunityOutput.findAll({
    where: { opportunityId, status: 'approved' },
    order: [['updatedAt', 'DESC']],
  });
}

async function loadAttachments({ bonfireOpportunityId }) {
  return OpportunityAttachment.findAll({
    where: { bonfireOpportunityId },
    order: [['downloaded_at', 'DESC']],
    attributes: { exclude: ['parsedText'] }, // we just need file metadata for the ZIP
  });
}

function readinessLineForReadme(readinessOut) {
  const c = readinessOut.counts || {};
  return `Readiness: ${readinessOut.completion_pct || 0}% complete · ${c.satisfied || 0}/${c.total || 0} required docs · ${c.gaps || 0} gap${c.gaps === 1 ? '' : 's'}`;
}

function buildReadme({ opp, vault, attachments, readinessOut, generatedAt }) {
  const lines = [
    `# Submission Package — ${opp.title || 'Bonfire Opportunity'}`,
    '',
    `**Agency**: ${opp.agency || '—'}  `,
    `**Opportunity ID**: ${opp.id}  `,
    opp.sourceUrl ? `**Original RFP**: ${opp.sourceUrl}  ` : null,
    opp.closeDate ? `**Close date**: ${new Date(opp.closeDate).toISOString().slice(0, 10)}  ` : null,
    `**Generated**: ${generatedAt.toISOString()}  `,
    '',
    `## Readiness`,
    '',
    readinessLineForReadme(readinessOut),
    '',
    `## Contents`,
    '',
    `### /vault — Evergreen + bid-local documents (${vault.length})`,
    '',
    ...vault.map((d) => `- ${d.scope === 'bid' ? '📌' : '🌐'} ${docTypes.labelFor(d.type)} — ${d.name} (v${d.version}${d.source === 'ai_generated' ? ', AI-generated' : ''})`),
    '',
    `### /attachments — RFP attachments scraped from Bonfire (${attachments.length})`,
    '',
    ...attachments.map((a) => `- ${a.name} (${a.mime || 'unknown'}, ${a.sizeBytes != null ? Math.round(a.sizeBytes / 1024) + ' KB' : 'unknown size'})`),
    '',
    `## Compliance checklist (from Submission Readiness)`,
    '',
    ...readinessOut.checklist.map((c) => {
      const tick = c.status === 'satisfied' ? '[x]' : '[ ]';
      const note = c.reason ? ` — ${c.reason}` : '';
      const src = c.source === 'ai' ? ' (AI-flagged)' : c.source === 'conditional' ? ' (rule)' : '';
      return `- ${tick} ${c.type_label}${src}${note}`;
    }),
    '',
    `---`,
    `Generated by Opportunity Pulse · Submission Readiness Engine v0.5.`,
    `Verify every requirement before clicking Submit & Finalize on the Bonfire portal.`,
    '',
  ].filter((x) => x !== null);
  return lines.join('\n');
}

function buildManifest({ opp, vault, attachments, readinessOut, generatedAt }) {
  return {
    schema_version: 1,
    generated_at: generatedAt.toISOString(),
    opportunity: {
      id: opp.id,
      title: opp.title,
      agency: opp.agency,
      source_url: opp.sourceUrl,
      close_date: opp.closeDate,
    },
    readiness: {
      completion_pct: readinessOut.completion_pct,
      counts: readinessOut.counts,
      checklist: readinessOut.checklist.map((c) => ({
        type: c.type, type_label: c.type_label, status: c.status, source: c.source, reason: c.reason,
      })),
    },
    vault: vault.map((d) => ({
      id: d.id, type: d.type, type_label: docTypes.labelFor(d.type),
      name: d.name, version: d.version, scope: d.scope, source: d.source,
      mime: d.mime, size_bytes: d.sizeBytes,
      expires_at: d.expiresAt, lineage_id: d.lineageId,
    })),
    attachments: attachments.map((a) => ({
      id: a.id, name: a.name, mime: a.mime, size_bytes: a.sizeBytes,
      url_original: a.urlOriginal, downloaded_at: a.downloadedAt,
    })),
  };
}

async function streamPackage({
  bonfireOpportunityId, organizationId = null, userId = null,
  res, // optional Express response — if provided, pipe directly
}) {
  const orgId = organizationId || (userId ? await profileSvc.resolveOrgId(userId) : 1);
  const opp = await BonfireOpportunity.findByPk(bonfireOpportunityId);
  if (!opp) {
    const err = new Error('Bonfire opportunity not found');
    err.code = 'NOT_FOUND';
    throw err;
  }

  const [vault, attachments, readinessOut] = await Promise.all([
    loadVaultDocsForOpp({ organizationId: orgId, bonfireOpportunityId }),
    loadAttachments({ bonfireOpportunityId }),
    readiness.computeReadiness({ opportunityId: bonfireOpportunityId, organizationId: orgId, userId }),
  ]);

  const generatedAt = new Date();
  // eslint-disable-next-line global-require
  const archiver = require('archiver');
  const archive = archiver('zip', { zlib: { level: 6 } });

  // If we have an Express res, pipe + set headers; otherwise return a Buffer.
  if (res) {
    const fname = `submission-package_${safeName(opp.title).replace(/\s+/g, '-')}_${generatedAt.toISOString().slice(0, 10)}.zip`;
    res.set('Content-Type', 'application/zip');
    res.set('Content-Disposition', `attachment; filename="${fname}"`);
    archive.pipe(res);
  }

  // README + manifest
  const readme = buildReadme({ opp, vault, attachments, readinessOut, generatedAt });
  archive.append(readme, { name: 'README.md' });
  const manifest = buildManifest({ opp, vault, attachments, readinessOut, generatedAt });
  archive.append(JSON.stringify(manifest, null, 2), { name: 'manifest.json' });

  // /vault — for each Document, emit the original file. If the doc is
  // markdown (AI-generated or uploaded text), ALSO emit a rendered PDF
  // so agency uploaders that want PDF-only have one without manual conversion.
  for (const d of vault) {
    let abs;
    try { abs = docStorage.absolutePathFor(d.filePath); }
    catch (e) {
      logger.warn('submissionPackage: skipping vault doc with bad path', { id: d.id, error: e.message });
      // eslint-disable-next-line no-continue
      continue;
    }
    if (!fs.existsSync(abs)) {
      logger.warn('submissionPackage: vault file missing on disk', { id: d.id, path: d.filePath });
      // eslint-disable-next-line no-continue
      continue;
    }
    const subdir = d.scope === 'bid' ? 'vault/bid-local' : 'vault/global';
    const outName = `${docTypes.labelFor(d.type)} — ${safeName(d.name)}${path.extname(d.filePath) || ''}`;
    archive.file(abs, { name: `${subdir}/${outName}` });

    if (d.mime === 'text/markdown' || /\.md$/i.test(d.filePath || '')) {
      try {
        const mdContent = fs.readFileSync(abs, 'utf8');
        const pdfBuf = await renderer.renderMarkdownToPdf(mdContent, {
          title: `${docTypes.labelFor(d.type)} · ${opp.title || ''}`,
        });
        const pdfName = `${docTypes.labelFor(d.type)} — ${safeName(d.name)}.pdf`;
        archive.append(pdfBuf, { name: `${subdir}/${pdfName}` });
      } catch (e) {
        logger.warn('submissionPackage: PDF render failed; markdown-only', { id: d.id, error: e.message });
      }
    }
  }

  // /attachments — original RFP files we scraped
  for (const a of attachments) {
    let abs;
    try { abs = attachStorage.attachmentAbsolutePath(a.filePath); }
    catch (_) { continue; }
    if (!fs.existsSync(abs)) continue;
    archive.file(abs, { name: `attachments/${safeName(a.name)}` });
  }

  await archive.finalize();
  return {
    bonfire_opportunity_id: bonfireOpportunityId,
    generated_at: generatedAt.toISOString(),
    counts: {
      vault: vault.length,
      attachments: attachments.length,
      readiness_pct: readinessOut.completion_pct,
    },
  };
}

module.exports = {
  streamPackage,
  buildReadme,
  buildManifest,
  safeName,
};
