// Deep Research Intelligence Engine — executive email briefing.
//
// FOUNDATION (Phase 1). Renders a daily executive briefing email from a
// set of deep research reports — top venture ideas, market reads, and
// links back to the full reports — and sends it via the existing email
// utility.
//
// Delivery is deliberately conservative for Phase 1: it only sends when a
// recipient is explicitly configured (DEEP_RESEARCH_BRIEFING_TO). With no
// recipient it returns { sent: false, reason: 'no_recipient' } and logs —
// so the daily scan can call it unconditionally without surprising anyone
// with email until it's deliberately turned on.

const { sendEmail } = require('../utils/email');
const logger = require('../logging/logger');

const APP_BASE_URL = process.env.APP_BASE_URL || 'http://95.216.199.47';

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Render the briefing HTML from an array of report objects (the shape
// returned by deepResearch.getReport). Pure — no I/O — so it's directly
// testable and reusable by a future in-app "preview briefing" view.
function buildBriefingHtml(reports = []) {
  const date = new Date().toISOString().slice(0, 10);
  const reportBlocks = (reports || []).map((r) => {
    const ideas = (r.ventureIdeas || []).slice(0, 3).map((v) => `
      <li style="margin:6px 0;">
        <strong>${esc(v.title)}</strong>
        <span style="color:#718096;">— ${esc(v.revenuePotential || 'medium')} revenue potential,
        ${esc(v.marketTiming || 'timing tbd')}</span><br/>
        <span style="color:#4a5568;font-size:13px;">${esc(v.description || '')}</span>
      </li>`).join('');
    return `
      <div style="border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:14px 0;">
        <div style="font-size:13px;color:#2b6cb0;text-transform:uppercase;letter-spacing:.05em;">
          ${esc(r.origin === 'daily_scan' ? 'Daily scan' : 'Research report')}
        </div>
        <h3 style="margin:4px 0 8px 0;color:#1a365d;">${esc(r.searchTerm)}</h3>
        <p style="margin:0 0 8px 0;color:#2d3748;">${esc(r.executiveSummary || 'Summary pending.')}</p>
        <div style="font-size:13px;color:#718096;margin-bottom:8px;">
          Market stage: <strong>${esc(r.marketStage || 'unknown')}</strong>
          &nbsp;·&nbsp; ${(r.ventureIdeas || []).length} venture ideas
          &nbsp;·&nbsp; ${esc(r.sourceCount || 0)} sources synthesized
        </div>
        ${ideas ? `<ul style="margin:8px 0;padding-left:18px;">${ideas}</ul>` : ''}
        <a href="${APP_BASE_URL}/admin/deep-research/${r.id}"
           style="display:inline-block;margin-top:6px;color:#2b6cb0;font-weight:600;">
          View full report →
        </a>
      </div>`;
  }).join('');

  return `<!doctype html><html><body style="font-family:-apple-system,Segoe UI,Arial,sans-serif;
    background:#f7fafc;margin:0;padding:24px;color:#2d3748;">
    <div style="max-width:680px;margin:0 auto;">
      <h1 style="color:#1a365d;font-size:22px;margin:0 0 4px 0;">Deep Research — Executive Briefing</h1>
      <p style="color:#718096;margin:0 0 16px 0;">${date} · Opportunity Pulse Venture Intelligence</p>
      ${reportBlocks || '<p style="color:#718096;">No new research reports today.</p>'}
      <p style="color:#a0aec0;font-size:12px;margin-top:24px;">
        Generated by the Deep Research Intelligence Engine. Phase 1 foundation.
      </p>
    </div></body></html>`;
}

// Send the daily executive briefing. Conservative delivery — see file header.
async function sendDailyBriefing(reports = [], options = {}) {
  const to = options.to || process.env.DEEP_RESEARCH_BRIEFING_TO || '';
  const html = buildBriefingHtml(reports);
  if (!to) {
    logger.info('emailBriefing: no recipient configured — briefing rendered but not sent', {
      reportCount: (reports || []).length,
    });
    return { sent: false, reason: 'no_recipient', html };
  }
  const subject = `Deep Research Briefing — ${new Date().toISOString().slice(0, 10)} `
    + `(${(reports || []).length} report${(reports || []).length === 1 ? '' : 's'})`;
  const result = await sendEmail({
    to,
    subject,
    html,
    text: `Deep Research executive briefing — ${(reports || []).length} reports. `
      + `View in app: ${APP_BASE_URL}/admin/opportunities/my`,
  });
  logger.info('emailBriefing: daily briefing dispatched', { to, sent: result.sent });
  return { ...result, html };
}

module.exports = {
  buildBriefingHtml,
  sendDailyBriefing,
};
